apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rmeqhzrj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rmeqhzrj:6bec195574c7bb90985751a3d9a63e6efbd5caa9@sha256:db86fe4e6fe939e4afe7e4e2fbbfe4d03916e1b4bb6f7db67f313fcd28a23226
          name: container-image
